### ISSUE TITLE
How to run this project

### ISSUE THREAD

**Issue by codingwatching** [sammyuri/minecraft#2]
Hi @sammyuri 
I try to run:
```
python3 main.py
```

But nothing happens, how to run this Minecraft project?
Thank you so much!

**Comment by farkon00** [comment]
It should output two schematic files bank1 and bank2. Then you need to paste them into a world with chungus2 computer. But you will need a special core for a server to run it in reasonoable speed. 

This is all based on  [this video](https://www.youtube.com/watch?v=xIMkqHb2-KM) and reading throw code.

**Comment by codingwatching** [comment]
@farkon00 Fantastic! Thank you I will try to learn about it now

**Comment by bitruss** [comment]
World download: https://www.mediafire.com/file/fbkuwo2aqg8gigj/3D+Minecraft+in+Minecraft.zip/file
World Web3 download: https://pz-rlhgrj.meson.network/ipfs/bafybeih6zvs54r6s6l6vx5j3x2owzcswmqxzpaej5obo3uiscaytry5azq/3D%20Minecraft%20in%20Minecraft.zip
